// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmduxmjyykklkcsqgbua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZHV4bWp5eWtrbGtjc3FnYnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MzQ2MDIsImV4cCI6MjA1MzMxMDYwMn0.0vym042kdRJ72amHozKmtpSCbf8-7afQGUjnCS7eOlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);